#!/usr/bin/env python3
"""Exercise the opt-in Canvas Studio using an isolated Chrome CDP session."""
import base64
import json
import os
from pathlib import Path
from qa_browser import Browser

port=int(os.environ.get('NOVA_QA_PORT','9237'))
origin=os.environ.get('NOVA_QA_URL','http://localhost:5177').rstrip('/')
out=Path('/private/tmp/nova-canvas-studio-20261003')
out.mkdir(exist_ok=True)
b=Browser(port,origin+'/projects')
def check(value,message):
    assert value,message
    print('PASS',message,flush=True)
def screenshot(name):
    b.pause(.4)
    result=b.call('Page.captureScreenshot',{'format':'png'})
    (out/(name+'.png')).write_bytes(base64.b64decode(result['data']))
def nav(path):
    b.call('Page.navigate',{'url':origin+path});b.wait_ready()
def saved():
    b.wait_for("!!document.querySelector('[aria-label=\"Saved on this device\"]')",8)
    b.pause(.6)
def snapshot():
    return b.evaluate("(async()=>{const {listProjects}=await import('/src/lib/localWorkspace.js');return (await listProjects()).find(p=>p.id===decodeURIComponent(location.pathname.split('/').at(-1)))})()",True)
def bounds(selector):
    return b.evaluate(f"(()=>{{const r=document.querySelector({json.dumps(selector)}).getBoundingClientRect();return {{x:r.x+r.width/2,y:r.y+r.height/2,w:r.width,h:r.height,left:r.left,right:r.right,top:r.top,bottom:r.bottom}}}})()")
try:
    b.call('Emulation.setDeviceMetricsOverride',{'width':1440,'height':960,'deviceScaleFactor':1,'mobile':False})
    b.evaluate("(async()=>{localStorage.setItem('nova-board-tour-v1','skipped');const {putProject}=await import('/src/lib/localWorkspace.js');const p={id:'qa-canvas-studio-source',title:'Studio QA source',created:100,updated:100,board:{nodes:[{id:1,x:700,y:650,title:'Original idea',note:'Preserve me',shape:'round',color:'violet',comments:[]}],edges:[]}};await putProject(p);return true})()",True)
    nav('/boards/qa-canvas-studio-source')
    b.wait_for("!!document.querySelector('[aria-label=\"Board canvas\"]')")
    check(not b.count('[aria-label="Canvas Studio"]'),'Normal board has no experimental controls')
    nav('/boards/qa-canvas-studio-source?studio=1')
    b.wait_for("!!document.querySelector('button[aria-label=\"Canvas Studio\"]')")
    saved();source=snapshot()
    b.click_aria('Canvas Studio');b.wait_for("!!document.querySelector('dialog[open]')")
    screenshot('launch')
    check(b.click_text('Create studio copy'),'Launch creates a separate copy')
    b.wait_for("!!document.querySelector('[data-studio-panel]')",10)
    check(b.click_text('Add starter experience'),'Add complete starter flow')
    b.wait_for("document.querySelectorAll('[data-studio-screen]').length===3")
    saved();copy=snapshot();copy_path=b.evaluate('location.pathname')
    original=b.evaluate("(async()=>{const {listProjects}=await import('/src/lib/localWorkspace.js');return (await listProjects()).find(p=>p.id==='qa-canvas-studio-source')})()",True)
    check(original["board"]==source["board"],'Original project is unchanged after creating and editing copy')
    check(copy['id']!=source['id'] and len(copy['board']['nodes'])==4,'Copy retains original content and saves three interactive screens')
    screenshot('editor-overview')
    b.click_text('Play prototype');b.wait_for("!!document.querySelector('dialog[aria-label=\"Prototype player\"][open]')")
    screenshot('player-explore')
    check(b.click_aria('Explore this place'),'Explore button is clickable')
    check(b.click_aria('Save this place'),'Details screen is interactive')
    b.wait_for("!!document.querySelector('dialog').innerText.includes('Saved places')")
    screenshot('player-saved')
    b.click_text('Show hotspots')
    check(b.evaluate("document.querySelector('dialog button[aria-pressed=\"true\"]').innerText.includes('Hide hotspots')"),'Hotspots can be highlighted')
    b.click_aria('Go back in prototype');b.wait_for("!!document.querySelector('dialog').innerText.includes('Place details')")
    b.click_aria('Restart prototype');b.wait_for("!!document.querySelector('dialog').innerText.includes('Explore')")
    b.click_aria('Close prototype player')
    b.click_aria('Select screen Explore')
    b.evaluate("document.querySelector('[data-studio-element=\"explore-heading\"]').click()")
    b.wait_for("!!document.querySelector('[data-studio-panel] textarea')")
    b.evaluate("document.querySelector('[data-studio-panel] textarea').focus()")
    b.fill('[data-studio-panel] textarea','A weekend worth remembering.')
    b.evaluate("document.querySelector('[data-studio-panel] textarea').blur()")
    saved()
    check('A weekend worth remembering.' in b.evaluate("[...document.querySelectorAll('[data-studio-screen] text')].map(el=>el.textContent).join(' ')"),'Content edit renders and saves')
    b.click_aria('Undo');saved()
    check('A little closer' in b.evaluate("[...document.querySelectorAll('[data-studio-screen] text')].map(el=>el.textContent).join(' ')"),'Undo restores screen content')
    b.click_aria('Redo');saved()
    check('A weekend worth remembering.' in b.evaluate("[...document.querySelectorAll('[data-studio-screen] text')].map(el=>el.textContent).join(' ')"),'Redo restores edited content')
    b.click_aria('Select screen Explore');b.pause(.2)
    start=bounds('[data-studio-element="explore-heading"]')
    before=snapshot()['board']['nodes'][1]['studio']['elements'][1]
    b.mouse_drag(start,{'x':start['x']+12,'y':start['y']+20});saved()
    after=snapshot()['board']['nodes'][1]['studio']['elements'][1]
    check(after['y']>before['y'],'Dragging an element updates its position')
    b.click_aria('Undo');saved()
    check(snapshot()['board']['nodes'][1]['studio']['elements'][1]['y']==before['y'],'One undo reverses a complete drag')
    b.click_aria('Select screen Explore');screenshot('editor-screen')
    # Wire the first button directly to the last screen and check the live player.
    b.evaluate("document.querySelector('[data-studio-element=\"explore-button\"]').click()")
    b.choose('[aria-label="Element click action"]','screen:'+str(copy['board']['nodes'][3]['id']))
    b.choose('[aria-label="Screen transition"]','fade');saved()
    b.click_text('Play prototype');b.click_aria('Explore this place')
    b.wait_for("!!document.querySelector('dialog').innerText.includes('Saved places')")
    check(True,'Changed target and transition work in player')
    b.click_aria('Close prototype player')
    b.call('Page.reload');b.wait_ready();b.wait_for("document.querySelectorAll('[data-studio-screen]').length===3")
    check('A weekend worth remembering.' in b.evaluate("[...document.querySelectorAll('[data-studio-screen] text')].map(el=>el.textContent).join(' ')"),'Prototype content survives reload')
    saved()
    # Read-only snapshot retains interactions and does not open the editing panel.
    link=b.evaluate("(async()=>{const {listProjects}=await import('/src/lib/localWorkspace.js');const {createShareUrl}=await import('/src/lib/boardShare.js');const p=(await listProjects()).find(p=>p.id===location.pathname.split('/').at(-1));return createShareUrl(p,location.origin,{access:'readonly'})})()",True)
    before_readonly=snapshot()
    b.call('Page.navigate',{'url':link});b.wait_ready();b.wait_for("!!document.querySelector('[data-readonly-board]')")
    check(not b.count('[data-studio-panel]'),'Read-only sharing has no editor')
    b.click_aria('Play prototype');b.click_aria('Explore this place');b.wait_for("!!document.querySelector('dialog').innerText.includes('Saved places')")
    check(True,'Read-only recipient can play prototype')
    b.click_aria('Close prototype player')
    readonly_saved=b.evaluate("(async()=>{const {listProjects}=await import('/src/lib/localWorkspace.js');return (await listProjects()).find(p=>p.id==="+json.dumps(before_readonly['id'])+")})()",True)
    check(readonly_saved==before_readonly,'Read-only playback does not write board data')
    nav(copy_path);b.wait_for("!!document.querySelector('[data-studio-panel]')")
    b.choose('[aria-label="Add a screen"]','desktop')
    b.wait_for("document.querySelectorAll('[data-studio-screen]').length===4")
    saved();desktop=snapshot()['board']['nodes'][-1]
    check(desktop['w']==960 and desktop['h']==640,'Desktop screen preset has correct dimensions')
    b.click_text('Card');saved()
    check(len(snapshot()['board']['nodes'][-1]['studio']['elements'])==4,'New elements can be added')
    b.click_text('Remove element');saved()
    check(len(snapshot()['board']['nodes'][-1]['studio']['elements'])==3,'Removing an element preserves the screen')
    b.click_text('Set as start');b.click_text('Play prototype')
    b.wait_for("!!document.querySelector('dialog').innerText.includes('Screen 4')")
    check(True,'Custom start screen is used by player')
    b.click_aria('Close prototype player')
    b.click_text('Duplicate screen');saved()
    check(len(snapshot()['board']['nodes'])==6,'Whole screen can be duplicated')
    b.click_text('Remove screen');saved()
    check(len(snapshot()['board']['nodes'])==5,'Remove screen deletes only selected screen')
    b.click_aria('Undo');saved()
    check(len(snapshot()['board']['nodes'])==6,'Undo restores a removed screen')
    b.click_aria('Select screen Screen 4 copy');b.click_text('Remove screen');saved()
    b.click_aria('Select screen Screen 4');b.click_text('Remove screen');saved()
    b.click_aria('Select screen Explore');b.click_text('Set as start');saved()
    # Escape dismisses the native player and returns focus to its trigger.
    b.evaluate("(()=>{const button=[...document.querySelectorAll('button')].find(el=>el.textContent.includes('Play prototype'));button.focus();button.click();return true})()")
    b.call('Input.dispatchKeyEvent',{'type':'keyDown','key':'Escape','code':'Escape','windowsVirtualKeyCode':27})
    b.call('Input.dispatchKeyEvent',{'type':'keyUp','key':'Escape','code':'Escape','windowsVirtualKeyCode':27})
    b.wait_for("!document.querySelector('dialog[open]')")
    check('Play prototype' in b.evaluate('document.activeElement.textContent'),'Player restores keyboard focus on Escape')
    for width,height in [(1280,800),(768,1024),(390,844),(320,740)]:
        b.call('Emulation.setDeviceMetricsOverride',{'width':width,'height':height,'deviceScaleFactor':1,'mobile':False});b.pause(.2)
        b.click_aria('Select screen Explore');b.pause(.2)
        panel=bounds('[data-studio-panel]')
        check(panel['left']>=0 and panel['right']<=width and panel['bottom']<=height,f'Studio panel fits {width}×{height}')
        if width==390:screenshot('mobile-editor')
        b.click_text('Play prototype');b.pause(.2)
        rect=bounds('dialog[open]');screen=bounds('dialog [data-studio-screen]')
        check(rect['left']>=0 and rect['right']<=width and rect['bottom']<=height and screen['left']>=rect['left'] and screen['right']<=rect['right'],f'Player fits {width}×{height}')
        if width==390:screenshot('mobile-player')
        b.click_aria('Close prototype player')
    check(not b.errors,'No browser runtime errors: '+str(b.errors))
    (out/'qa-project.json').write_text(json.dumps({'copyPath':copy_path,'port':port}))
    print('Screenshots:',out,flush=True)
finally:
    b.close()
